SafetyCulture/safetyculture-exporter-ui

.github/workflows/build.yml, frontend/package-lock.json, frontend/package.json, scripts/build-windows.sh
Build for windows using ubuntu platform
=> INTG-2625 cgo enabled

frontend/src/components/StatusBar.svelte, frontend/src/lib/utils.js, go.mod, go.sum
Check if the GitHub returns error (NULL response), then make sure the application is handling this
=> INTG-2636 protection when GitHub fails

frontend/src/routes/TemplateFilter.svelte
=> INTG-2645 templates title

go.mod, go.sum, scripts/build-windows.sh
=> INTG-2622 tests for build

README.md
replace the wails default Readme
=> INTG-2650 readme startup

frontend/src/components/Button.svelte, frontend/src/components/FormPassword.svelte, frontend/src/components/ValidatablePassword.svelte, frontend/src/routes/Config.svelte, frontend/src/routes/ExportStatus.svelte, frontend/src/routes/FeedFilter.svelte, frontend/src/routes/TemplateFilter.svelte, frontend/src/routes/Welcome.svelte
This fixes
- Clear password field
- Button style on cancel export button
- Will only render `Open Export Folder` button for csv export.
=> INTG-2648 - Code clean, style fixes.

frontend/src/routes/FeedFilter.svelte, frontend/src/routes/TemplateFilter.svelte
fix header checkbox to uncheck when body checkbox is unticked
=> INTG-2655 toggle header checkbox

frontend/src/routes/Config.svelte, frontend/src/routes/common.css
this PR:
- add css to export folder
- hide export folder selection if export format is not 'csv' type
- re-ordered the css commons alphabetically
=> INTG-2655 export folder css changes

frontend/src/components/Button.svelte, frontend/src/components/Export/Pill.svelte, frontend/src/routes/ExportStatus.svelte, frontend/src/routes/common.css
* changed the layout to correspond to the new design:
Possible statuses: new colours
Rounded corner for table
Remove SafetyCulture logo
Add title to page: Export status
Move in progress next to Cancel export
Remove Progress column title
Cancel export button colour
=> INTG-2665 export status tuning

frontend/src/routes/TemplateFilter.svelte, frontend/src/routes/common.css
this PR:
- change template page checkbox colour
- remove loading/complete icon
=> INTG-2664 template page feedback changes changes

.github/workflows/build.yml
Temporarily disable mac version from build workflow. To be addressed and reintroduced in exporter-ui v2
=> INTG-2671 disable mac from build workflow

frontend/src/components/StatusBar.svelte, go.mod, go.sum
Add a safeguard if the download url is missing
=> INTG-2679 display the download only when there is a URL

frontend/src/components/Button.svelte, frontend/src/routes/Welcome.svelte
The Verify button should temporarily disable the functionality while checking/waiting for the backend
=> INTG-2675 add a state to the verify button

frontend/src/App.svelte, frontend/src/routes/Config.svelte, frontend/src/routes/DataSetFilter.svelte
Change the wording from tables to data sets
=> INTG-2678 wording for tables

internal/version/version.go, internal/version/version_test.go
treat certain edge cases:
* current version has typos
* always suggest update from PRE
=> INTG-2694 update to versioning

.github/workflows/build.yml, .gitignore, README.md, app.go, frontend/src/components/ValidatableNumberInput.svelte, frontend/src/lib/store.js, frontend/src/routes/common.css, main.go
Clean-up css classes, unused variables, redundant bits
=> INTG-2662 clean before work

frontend/src/components/StatusBar.svelte, frontend/src/routes/Config.svelte, main.go
Updated icon on the report format dropdown, copyright notice in the status bar.
=> INTG-2697 - Updated icon on the report format dropdown, copyright notice in the status bar.

.github/workflows/build.yml, go.mod, go.sum
=> INTG-2698 linux build

.github/workflows/build.yml
=> build updates

frontend/src/components/FolderPicker.svelte, frontend/src/routes/Config.svelte, frontend/src/routes/common.css
Show a tooltip if the folder location is too long
=> INTG-2682 tooltip

frontend/src/routes/Config.svelte
Correct issue with export all tables + media
=> INTG-2713 fix table select

README.md
Update readme to include the link to the doc
=> INTG-2650 add readme link

frontend/src/lib/utils.js, frontend/src/routes/DataSetFilter.svelte, go.mod, go.sum
Adds action timeline items and issue timeline items to the data feed table.
---
=> INTG-2230 add data feeds - action timeline, issue timeline

frontend/src/routes/Config.svelte, go.sum
apply folder check to reports and sqlite
---
=> INTG-2820 fix reports

go.mod, go.sum
This PR updates the repo to use the latest safetyculture-exporter package.
The changes allow for specifying a start_date when fetching the scheduled occurrences. The respective end_date is explicitly set to 31 days from the start_date.
---
=> [RELAY-2505] Update safetyculture-exporter package

frontend/src/routes/DataSetFilter.svelte
=> INTG-3078 upd label

app.go, frontend/src/routes/Init.svelte
Improve the way we check the validation for the API KEY
A bug was introduced a while ago with relation to api-key checking
- ...
---
=> INTG-3224 fix api key validation

go.mod, go.sum
=> INTG-3307 - added note field to schedule occurrences

.github/workflows/build.yml
Update the GitHub Actions build
- ...
---
=> DEVP-3557 upd GitHub Actions versions

frontend/src/routes/Welcome.svelte
Some configurations of resolution and scale cause the api token input to be hidden. This PR adds a scroll to the welcome page to allow for adjustments.
- ...
---
=> PROBLEM-3777 adjust welcome page css

frontend/src/components/StatusBar.svelte, frontend/src/routes/Welcome.svelte, frontend/src/style.css, main.go
The window is currently fixed in size, causing some configurations to shift components off the visible window and stay hidden. This PR adds window resisability and scrolling for additional accessibility.
- ...
---
=> PROBLEM-3777 add window resize and scrolling

go.mod, go.sum
=> DEVP-3825 - bumped version - added created_at to the users feed data.
